env:
#  - TOXENV=py26
#  - TOXENV=py27
#  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=lint
#  - TOXENV=docs
install:
  - pip install tox
script:
  - tox
matrix:
  allow_failures:
    - env: TOXENV=lint
#    - env: TOXENV=docs
sudo: false